services:
  i9script-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: i9script-website
    ports:
      - "4444:80"
    volumes:
      # Volume para desenvolvimento - permite hot reload
      - ./:/usr/share/nginx/html/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - TZ=America/Manaus
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "com.i9script.description=i9Script Website Container"
      - "com.i9script.version=1.0"

  # Serviço opcional para logs e monitoramento
  nginx-logs:
    image: busybox:latest
    container_name: i9script-logs
    volumes:
      - logs-volume:/var/log/nginx
    command: sh -c "sleep 10 && tail -f /var/log/nginx/access.log /var/log/nginx/error.log 2>/dev/null || echo 'Aguardando logs...'"
    depends_on:
      - i9script-web
    restart: unless-stopped
    labels:
      - "com.i9script.description=i9Script Logs Monitor"

volumes:
  logs-volume:
    name: i9script-logs
    driver: local